name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag brunohenriqueruas/build:$(date +%s)
    - name: docker login
      run: | # logar na conta
        docker login -u brunohenriqueruas -p 0b836632-0806-4b11-bceb-bf5ed46b958e
    - name: docker login
      run: |
        docker push  brunohenriqueruas/build:$(date +%s)
