name: Workflow de teste

on: push

jobs:
  meu_job_1:
    name: Meu Job 1
    runs-on: ubuntu-latest
    steps:        
      - name: Meu primeiro step
        run: |
          echo "Funciona o primeiro step"   
           
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: winnin/desafio

      - name: Cache release dist
        id: cache-release-dist
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.os }}-${{github.run_number}}-release-dist   

      - name: Listando dir
        run: |
          pwd
          ls
      



