name: Workflow de teste

on: push

jobs:
  meu_job_1:
    name: Meu Job 1
    runs-on: ubuntu-latest
    steps:        
      - name: Meu primeiro step
        run: |
          echo "Funciona o primeiro step"   
           
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: winnin/desafio

      - name: Cache teste
        id: cache-teste
        uses: actions/cache@v2
        with:
          path: "/home/runner/work/lab-bruno/lab-bruno"
          key: LAB_TEMP

      - name: Listando dir
        run: |
          pwd
          ls

  meu_job_2:
    name: Meu job 2
    runs-on: ubuntu-latest
    steps:
       - name: Meu segundo step
         run: | 
           echo "Cache teste: ${{steps.cache-teste.outputs.cache-teste}}"
           cd "/home/runner/work/lab-bruno/lab-bruno"
          
        



