name: Workflow de teste

on: push

jobs:
  meu_job_1:
    name: Meu Job 1
    runs-on: ubuntu-latest
    steps:      

      - name: Meu primeiro step
        run: |
          echo "Funciona o primeiro step"
      
      - name: Cache teste
      	id: cache-teste
      	uses: actions/cache@v2
      	with:
          path: winnin/desafio
          key: ${{ runner.os }}-teste
          
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: winnin/desafio

      - name: Listando dir
        run: |
          pwd
          ls




