name: Workflow de teste

on: push


jobs:
  meu_job_1:
    name: Meu Job 1
    runs-on: ubuntu-latest
    outputs:
      eligible_release: ${{ steps.parse_release_tag_name.outputs.release_tag }}
                            
    steps:        
      - name: Meu primeiro step
        run: |
          echo "Funciona o primeiro step"   
           
      - name: Checkout
        uses: actions/checkout@v2
        ref: ${{ steps.release_download.outputs.release_tag }}
        with:
          repository: winnin/desafio
          path: cache 

      - name: Listando dir 
        run: |
          pwd
          ls
          ls cache    

      - name: Cache teste
        uses: actions/cache@v2
        with:
          path: cache
          key: chave_teste

      
  meu_job_2:
    name: Meu job 2
    runs-on: ubuntu-latest
    steps:
       - name: Meu segundo step
         run: | 
           pwd
           ls

       - name: Cache teste
         uses: actions/cache@v2
         with:
          path: cache2
          key: chave_teste2

       - name: Meu segundo step
         run: | 
           pwd
           ls

       - name: Check Out Repo
         uses: actions/checkout@v2
        

       - name: Parse release tag name
         id: parse_release_tag_name
         run: |
          RELEASE_TAG=$( echo ${{ steps.release_download.outputs.release_tag }}
          echo "::set-output name=release_tag::$RELEASE_TAG"       

       - name: Meu segundo step
         run: | 
           pwd
           ls    

       - name: Cache teste tras dados
         uses: actions/cache@v2
         with:
          path: cache
          key: chave_teste

       - name: Meu segundo step
         run: | 
           pwd
           ls 
           ls cache

               