name: Workflow de teste

on: push


jobs:
  meu_job_1:
    name: Meu Job 1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.job1_set_output.outputs.output1 }}}
                            
    steps:

      - name: Set output
        id: job1_set_output
        run: |
          OUTPUT="MyOutput"
          echo "::set-output name=output1::$OUTPUT"            
      - name: Meu primeiro step
        run: |
          echo "Funciona o primeiro step"   
           
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: winnin/desafio
          path: cache 

      - name: Listando dir 
        run: |
          pwd
          ls
          ls cache    

      - name: Cache teste
        uses: actions/cache@v2
        with:
          path: cache
          key: chave_teste

      
  meu_job_2:
    name: Meu job 2
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
       - name: Meu segundo step
         run: | 
           pwd
           ls

       - name: Cache teste
         uses: actions/cache@v2
         with:
          path: cache2
          key: chave_teste2

       - name: Meu segundo step
         run: | 
           pwd
           ls

       - name: Check Out Repo
         uses: actions/checkout@v2
        
       - name: job2
       - name: Echo job1 output  
         run: |
           echo ${{ needs.job1.outputs.output1 }}
                 
       - name: Meu segundo step
         run: | 
           pwd
           ls    

       - name: Cache teste tras dados
         uses: actions/cache@v2
         with:
          path: cache
          key: chave_teste

       - name: Meu segundo step
         run: | 
           pwd
           ls 
           ls cache

               







               